development:
  adapter: postgresql
  encoding: utf8
  database: learn_rails_development
  pool: 5
  username: Zeke
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: learn_rails_test
  pool: 5
  username: Zeke
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: learn_rails_production
  pool: 5
  username: Zeke
  password: